package net.solooo.template.entity;

public class Company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.Id
     *
     * @mbg.generated Fri Jun 09 15:10:38 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.company_name
     *
     * @mbg.generated Fri Jun 09 15:10:38 CST 2017
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.company_address
     *
     * @mbg.generated Fri Jun 09 15:10:38 CST 2017
     */
    private String companyAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.Id
     *
     * @return the value of COMPANY.Id
     *
     * @mbg.generated Fri Jun 09 15:10:38 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.Id
     *
     * @param id the value for COMPANY.Id
     *
     * @mbg.generated Fri Jun 09 15:10:38 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.company_name
     *
     * @return the value of COMPANY.company_name
     *
     * @mbg.generated Fri Jun 09 15:10:38 CST 2017
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.company_name
     *
     * @param companyName the value for COMPANY.company_name
     *
     * @mbg.generated Fri Jun 09 15:10:38 CST 2017
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.company_address
     *
     * @return the value of COMPANY.company_address
     *
     * @mbg.generated Fri Jun 09 15:10:38 CST 2017
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.company_address
     *
     * @param companyAddress the value for COMPANY.company_address
     *
     * @mbg.generated Fri Jun 09 15:10:38 CST 2017
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress;
    }
}