package net.solooo.template.entity;

public class Person {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.Id
     *
     * @mbg.generated Fri Jun 09 15:10:38 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.name
     *
     * @mbg.generated Fri Jun 09 15:10:38 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.age
     *
     * @mbg.generated Fri Jun 09 15:10:38 CST 2017
     */
    private Short age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.Id
     *
     * @return the value of PERSON.Id
     *
     * @mbg.generated Fri Jun 09 15:10:38 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.Id
     *
     * @param id the value for PERSON.Id
     *
     * @mbg.generated Fri Jun 09 15:10:38 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.name
     *
     * @return the value of PERSON.name
     *
     * @mbg.generated Fri Jun 09 15:10:38 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.name
     *
     * @param name the value for PERSON.name
     *
     * @mbg.generated Fri Jun 09 15:10:38 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.age
     *
     * @return the value of PERSON.age
     *
     * @mbg.generated Fri Jun 09 15:10:38 CST 2017
     */
    public Short getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.age
     *
     * @param age the value for PERSON.age
     *
     * @mbg.generated Fri Jun 09 15:10:38 CST 2017
     */
    public void setAge(Short age) {
        this.age = age;
    }
}